name: 开发者帮助 / Development Help
description: 汇报问题或请求开发帮助（仅限开发者）。 / Report issues or ask for help on development. (For developers only)
labels: [ "dev" ]
title: "[dev] "
body:
  - type: markdown
    attributes:
      value: |
        感谢给 QAuxiliary 汇报问题！
        为了使我们更好地帮助你，请提供以下信息。
  - type: textarea
    attributes:
      label: 描述 / Description
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: checkboxes
    id: latest
    attributes:
      label: 其他要求 / Other Requirements
      options:
        - label: 我已经在 [Issue Tracker](https://github.com/cinit/QAuxiliary/issues) 中找过我要提出的问题，没有找到相同问题。重复问题会被关闭。
          required: true
        - label: 我知晓此 Issue 模板仅限开发者使用，普通用户请使用问题反馈或功能请求模板。 / I know this issue template is for developers only. Regular users should use the bug report or feature request template.
          required: true
